### ISSUE TITLE
$WEBRTC_HOME not set, .jar file missing

### ISSUE THREAD

**Issue by lgrahl** [pristineio/webrtc-build-scripts#79]
The readme states:

```
When the scripts are done you can find the .jar and .so file in
$WEBRTC_HOME under "libjingle_peerconnection_builds".
```

That variable does not exist. I also can't find a file named ``libjingle_peerconnection.jar`` anywhere. However, there are two files named ``libjingle_peerconnection_java.jar`` which are identical:

```
webrtc-build-scripts/android/webrtc/src/out_android_armeabi-v7a/Release/gen/libjingle_peerconnection_java
webrtc-build-scripts/android/webrtc/src/out_android_armeabi-v7a/Release/lib.java/libjingle_peerconnection_java.jar
```

**Comment by aaalaniz** [comment]
Good find. This issue has been resolved in latest. Thanks!

**Comment by lgrahl** [comment]
Great stuff! However, the variable ``$WEBRTC_HOME`` still does not exist. I guess the readme just needs an update there.

**Comment by aaalaniz** [comment]
oops sorry....it's WEBRTC_ROOT. I will update the README
